{
 "title": "Promet",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{kafka_version=\"3.4.0\"}",
     "legendFormat": "time(ms)"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "kafka_producer_request_rate", "legendFormat": "Producer" },
    { "expr": "kafka_consumer_request_rate", "legendFormat": "Consumer" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_error_total",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}